language: objective-c
branches:
  only:
    - master
cache:
  directories:
  - /usr/local/Homebrew
  - $HOME/Library/Caches/Homebrew
before_cache:
  - brew cleanup
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
jobs:
  include:
  - stage: "Builds"
    osx_image: xcode9.4
    script: xcodebuild -scheme FloatingPanel SWIFT_VERSION=4.1 clean build
    name: "Swift 4.1"
  - script: xcodebuild -scheme FloatingPanel SWIFT_VERSION=4.2 clean build
    osx_image: xcode10
    name: "Swift 4.2"
  - script: xcodebuild -scheme FloatingPanel SWIFT_VERSION=5.0 clean build
    osx_image: xcode10.2
    name: "Swift 5.0"

  - stage: "Tests"
    osx_image: xcode10.2
    script: xcodebuild clean test -scheme FloatingPanel -workspace FloatingPanel.xcworkspace -destination 'platform=iOS Simulator,OS=10.3.1,name=iPhone SE'
    name: "iPhone SE (iOS 10.3)"
  - script: xcodebuild clean test -scheme FloatingPanel -workspace FloatingPanel.xcworkspace -destination 'platform=iOS Simulator,OS=11.4,name=iPhone 7'
    osx_image: xcode10.2
    name: "iPhone 7 (iOS 11.4)"
  - script: xcodebuild clean test -scheme FloatingPanel -workspace FloatingPanel.xcworkspace -destination 'platform=iOS Simulator,OS=12.2,name=iPhone X'
    osx_image: xcode10.2
    name: "iPhone X (iOS 12.2)"

  - stage: Build examples
    osx_image: xcode10.2
    script: xcodebuild -scheme Maps -sdk iphonesimulator clean build
    name: "Maps"
  - script: xcodebuild -scheme Stocks -sdk iphonesimulator clean build
    osx_image: xcode10.2
    name: "Stocks"
  - script: xcodebuild -scheme Samples -sdk iphonesimulator clean build
    osx_image: xcode10.2
    name: "Samples"

  - stage: Carthage
    osx_image: xcode10.2
    before_install:
    - brew update
    - brew outdated carthage || brew upgrade carthage
    script:
    - carthage build --no-skip-current

  - stage: CocoaPods
    osx_image: xcode10.2
    script:
    - pod spec lint --allow-warnings
    - pod lib lint --allow-warnings
